# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e1fb77f0ba07b5cb77c50942f894d0d79958c364587188c0d4f15bedc698e0f5a3e6f9941a2a692b3e7c27129a2e33db9d8325ca9aefadfe398e5b4431ab45

test:
  secret_key_base: 59d512c73dd0d515fe726f97fca1470f1036b1880ba5636f66511f0ea03e6b18b8841c9807134019eeb7344deaff4653f08c64a6bbc2422fd86e3ec6a8bb7c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
